---
detectors:
  Attribute:
    enabled: false

  ControlParameter:
    enabled: false

  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  UncommunicativeVariableName:
    accept:
      - e