---
detectors:
  Attribute:
    enabled: false

  ControlParameter:
    enabled: false

  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  UncommunicativeVariableName:
    accept:
      - e
      - _
      - id1
      - id2

  UncommunicativeParameterName:
    accept:
      - id1
      - id2
      - ids1
      - ids2
      - version1
      - version2
